### ISSUE TITLE
Missing licensing terms?

### ISSUE THREAD

**Issue by RomainMuller** [bytecodealliance/spidermonkey-wasm-rs#38]
Hey!

I'd like to know what license this code is released on, in order to determine whether it would be suitable for derivatives...

Right now, neither the Cargo.toml nor repo mention any license, which makes it default to opaque copyright (that's sad....)

**Comment by saulecabrera** [comment]
Added in https://github.com/bytecodealliance/spidermonkey-wasm-rs/pull/39
